//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public items()
        {
            this.request = new HashSet<request>();
        }
    
        public int item_id { get; set; }
        public int owner_id { get; set; }
        public string item_name { get; set; }
        public int category_id { get; set; }
        public string description { get; set; }
        public System.DateTime date_posted { get; set; }
    
        public virtual category category { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<request> request { get; set; }
    }
}
