//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SharedShelfDBEntities1 : DbContext
    {
        public SharedShelfDBEntities1()
            : base("name=SharedShelfDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<items> items { get; set; }
        public DbSet<request> request { get; set; }
        public DbSet<request_status> request_status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<transaction_status> transaction_status { get; set; }
        public DbSet<transactions> transactions { get; set; }
        public DbSet<user_auth> user_auth { get; set; }
        public DbSet<users> users { get; set; }
    }
}
