//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public request()
        {
            this.transactions = new HashSet<transactions>();
        }
    
        public int request_id { get; set; }
        public int borrower_id { get; set; }
        public System.DateTime borrow_date { get; set; }
        public System.DateTime return_date { get; set; }
        public System.DateTime created_at { get; set; }
        public int item_id { get; set; }
        public int status_id { get; set; }
    
        public virtual items items { get; set; }
        public virtual request_status request_status { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
