//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public int transaction_id { get; set; }
        public int request_id { get; set; }
        public Nullable<decimal> late_fee { get; set; }
        public int status_id { get; set; }
    
        public virtual request request { get; set; }
        public virtual transaction_status transaction_status { get; set; }
    }
}
