//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_status
    {
        public transaction_status()
        {
            this.transactions = new HashSet<transactions>();
        }
    
        public int status_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<transactions> transactions { get; set; }
    }
}
