//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_auth
    {
        public user_auth()
        {
            this.users = new HashSet<users>();
        }
    
        public int user_auth_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public System.DateTime created_at { get; set; }
        public string user_type { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
