//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedShelf
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.items = new HashSet<items>();
            this.request = new HashSet<request>();
        }
    
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public int user_auth_id { get; set; }
    
        public virtual ICollection<items> items { get; set; }
        public virtual ICollection<request> request { get; set; }
        public virtual user_auth user_auth { get; set; }
    }
}
